steps:
  # Step 1: Construir la imagen Docker
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$_NAME:$COMMIT_SHA", "."]

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/$_NAME:$COMMIT_SHA"]

  # Cloud Run Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy',
      '$_NAME-$_ENV',
      '--image',
      'gcr.io/$PROJECT_ID/$_NAME:$COMMIT_SHA',
      '--platform',
      'managed',
      '--region',
      'us-east1',
      '--use-http2',
      '--port=8080',
      '--min-instances=1',
      '--max-instances=10',
      '--session-affinity',
      '--no-cpu-throttling',
      '--no-invoker-iam-check',
      '--set-cloudsql-instances',
      'muy-admin:us-east1:pgdb',
      '--set-secrets',
      'PG_DATABASE_URL=PG_DATABASE_URL:1',
      '--set-secrets',
      'WHATSAPP_TOKEN=WHATSAPP_TOKEN:1',
      '--set-secrets',
      'WHATSAPP_PHONE=WHATSAPP_PHONE:1',
      '--set-secrets',
      'GOOGLE_MAPS_API_KEY=GOOGLE_MAPS_API_KEY:2',
      '--service-account',
      '133490397562-compute@developer.gserviceaccount.com',
    ]

images:
  - "gcr.io/$PROJECT_ID/$_NAME:$COMMIT_SHA"

substitutions:
  _ENV: "dev"
  _NAME: "mdc-apigo-rest"

options:
  logging: CLOUD_LOGGING_ONLY
